on:
  push:
    branches:
      - main

name: Deploy via ftp

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp.mfhscholarship.com
          user: u426145892.admin
          password: Codehubsoftuk7866@
         
